#!/bin/sh

$HOME/dotfiles/autostart.sh

sxhkd &
#compton &

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config normal_border_color "#484848"
bspc config focused_border_color "#1F8999"
bspc config border_width         3

bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a albert focus=on border=off

bspc rule -a Firefox desktop='^1' follow=true
bspc rule -a nvim-qt desktop='^2' follow=true
bspc rule -a jetbrains-idea-ce desktop='^3'
bspc rule -a Chromium desktop='^3'
bspc rule -a mpv follow=true border=off
bspc rule -a Pidgin desktop='^5'
bspc rule -a Transmission desktop='^6'
bspc rule -a lisons desktop='^7' follow=true
bspc rule -a thunar desktop='^8' follow=true
bspc rule -a Sxiv fullscreen=true
bspc rule -a Qalculate-gtk state=floating
